/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;
import ptraitement.Jeu;
import ptraitement.Joueur;

/**
 *
 * @author hugor
 */
public class Faccueil extends javax.swing.JFrame {
    private Fjeu fichJeu;
    private Jeu monJeu;
    protected String pseudo1;
    protected String pseudo2;

    
    public Faccueil() {
        initComponents();
        this.setLocation(560,220);
        
    }
    public Fjeu getFichJeu(){return fichJeu;}
    public Jeu getMonJeu(){return monJeu;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGnbjoueur = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RB1joueur = new javax.swing.JRadioButton();
        RB2joueurs = new javax.swing.JRadioButton();
        Tpseudo1 = new javax.swing.JTextField();
        Lpseudo1 = new javax.swing.JLabel();
        Bcommencer = new javax.swing.JButton();
        Lpseudo2 = new javax.swing.JLabel();
        Tpseudo2 = new javax.swing.JTextField();
        CBchargement = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jeu De Chateau");

        BGnbjoueur.add(RB1joueur);
        RB1joueur.setText("Joueur contre Ordinateur");
        RB1joueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1joueurActionPerformed(evt);
            }
        });

        BGnbjoueur.add(RB2joueurs);
        RB2joueurs.setSelected(true);
        RB2joueurs.setText("Joueur contre Joueur");
        RB2joueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2joueursActionPerformed(evt);
            }
        });

        Tpseudo1.setToolTipText("");

        Lpseudo1.setText("Insérer le pseudo du joueur 1!");

        Bcommencer.setText("COMMENCER");
        Bcommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcommencerActionPerformed(evt);
            }
        });

        Lpseudo2.setText("Insérer le pseudo du joueur 2!");

        Tpseudo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tpseudo2ActionPerformed(evt);
            }
        });

        CBchargement.setText("Charger Partie?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lpseudo2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tpseudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lpseudo1)
                                    .addComponent(Tpseudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CBchargement)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bcommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(RB1joueur, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(RB2joueurs, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Lpseudo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tpseudo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB2joueurs))
                .addGap(31, 31, 31)
                .addComponent(Lpseudo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB1joueur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tpseudo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBchargement))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tpseudo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tpseudo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tpseudo2ActionPerformed

    private void RB1joueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1joueurActionPerformed
        Tpseudo2.setEnabled(false);
        Tpseudo2.setText("Ordinateur");
    }//GEN-LAST:event_RB1joueurActionPerformed

    private void BcommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcommencerActionPerformed
        pseudo1 = Tpseudo1.getText();
        pseudo2 = Tpseudo2.getText();
        fichJeu = new Fjeu(this,false);
        fichJeu.setLocationRelativeTo(null);
        System.out.println(pseudo1 + " " +  pseudo2);
        this.setVisible(false);
        fichJeu.setVisible(true);
    }//GEN-LAST:event_BcommencerActionPerformed

    private void RB2joueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2joueursActionPerformed
        Tpseudo2.setEnabled(true);
        Tpseudo2.setText("");
    }//GEN-LAST:event_RB2joueursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faccueil().setVisible(true);
            }
        });
    }
    
    public String getPseudo1(){return pseudo1;}
    public String getPseudo2(){return pseudo2;}
    public boolean getCBchargement(){return CBchargement.isSelected();}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGnbjoueur;
    private javax.swing.JButton Bcommencer;
    private javax.swing.JCheckBox CBchargement;
    private javax.swing.JLabel Lpseudo1;
    private javax.swing.JLabel Lpseudo2;
    private javax.swing.JRadioButton RB1joueur;
    private javax.swing.JRadioButton RB2joueurs;
    private javax.swing.JTextField Tpseudo1;
    private javax.swing.JTextField Tpseudo2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
